#1 AÑO DE MERCURIO SON 88 DIAS
#1 AÑO DE VENUS SON 225 DIAS
#1 AÑO EN TIERRA SON 365 DIAS
#1 AÑO DE MARTE SON 687 DIAS
#1 AÑO DE JUPiTER SON 4329 DIAS
#1 AÑO DE SATURNO SON 10585 DIAS
#1 AÑO DE URANO SON 30660 DIAS
#1 AÑO DE NEPTUNO SON 60190  DIAS
#1 AÑO DE PLUTON SON 90520 DIAS

print("Ingresa tus años de edad")
edad =int(input())
mercurio = int(88)
venus = int(255)
tierra = int(365)
marte = int(687)
jupiter = int(4329)
saturno = int (10585)
urano = int(30660)
neptuno = int(60190)
pluton = int(90520)

print("***** Tus años de edad en mercurio son: ",edad*mercurio,"*****")
print("")
print("***** Tus años de edad en mercurio son: ",edad*venus,"*****")
print("")
print("***** Tus años de edad en mercurio son: ",edad*tierra,"DIAS","*****")
print("")
print("***** Tus años de edad en mercurio son: ",edad*marte,"DIAS","*****")
print("")
print("***** Tus años de edad en mercurio son: ",edad*jupiter,"DIAS","*****")
print("")
print("***** Tus años de edad en mercurio son: ",edad*saturno,"DIAS","*****")
print("")
print("***** Tus años de edad en mercurio son: ",edad*urano,"DIAS","*****")
print("")
print("***** Tus años de edad en mercurio son: ",edad*neptuno,"DIAS","26*****")
print("")
print("***** Tus años de edad en mercurio son: ",edad*pluton,"DIAS","*****")
print("")
print("VETE A OTRO PAIS Y DURARAS MAS (^u^)")
