def OPERACION_SUMA():
    print("SUMA")
    print("Ingresa el valor de A")
    a=int(input())
    print("Ingresa el valor de B")
    b=int(input())
    resultado = a+b
    print("El resultado de la suma es: ", resultado)

def OPERACION_RESTA():
    print("RESTA")
    print("Ingresa el valor de A")
    a=int(input())
    print("Ingresa el valor de B")
    b=int(input())
    resultado = a-b
    print("El resultado de la RESTA es: ", resultado)

def OPERACION_MULTIPLICACION():
    print("MULTIPLICACION")
    print("Ingresa el valor de A")
    a=int(input())
    print("Ingresa el valor de B")
    b=int(input())
    resultado = a*b
    print("El resultado de la MULTIPLICACION es: ", resultado)

def OPERACION_DIVICION():
    print("DIVICION")
    print("Ingresa el valor de A")
    a=int(input())
    print("Ingresa el valor de B")
    b=int(input())
    resultado = a/b
    print("El resultado de la DIVICION es: ", resultado)
    
#def argumentos(nombre,edad):
#    print ("Mi nombre es: ",nombre, "y mi edad",edad, "años")

#print("INGRESA 1 PARA SUMA, 2 PARA RESTA, 3 PARA MULTIPLICIACION O 4 PARA DIVICION")
#opcion=int(input())
#if opcion == 1:
#      OPERACION_SUMA()
#elif opcion == 2:
#        OPERACION_RESTA()
#elif opcion == 3:
#        OPERACION_MULTIPLICACION()
#elif opcion == 4:
#        OPERACION_DIVICION()
#else:
#    print ("Opción no válida")


