import tkinter as tk
window = tk.Tk()
window.title("JUEGO DE GATO (^<^)")

entry = tk.Entry(window) #PARA ESCRIBIR DATO APELLIDO
entry.grid(row=0, column=0,padx=10,pady=10)  # CAJA DE ENTRADA FILA 1 COLUMNA 3
entry.config(bg="yellow", font="bold", border=10)# CAJA DE ENTRADA FILA 1 COLUMNA 0
#***********************************************************************************
entry = tk.Entry(window) #PARA ESCRIBIR DATO APELLIDO
entry.grid(row=0, column=1,padx=10,pady=10)  # CAJA DE ENTRADA FILA 1 COLUMNA 3
entry.config(bg="yellow", font="bold", border=10)# CAJA DE ENTRADA FILA 1 COLUMNA 0
#***********************************************************************************
entry = tk.Entry(window) #PARA ESCRIBIR DATO APELLIDO
entry.grid(row=0, column=2,padx=10,pady=10)  # CAJA DE ENTRADA FILA 1 COLUMNA 3
entry.config(bg="yellow", font="bold", border=10)# CAJA DE ENTRADA FILA 1 COLUMNA 0
#***********************************************************************************
entry = tk.Entry(window) #PARA ESCRIBIR DATO APELLIDO
entry.grid(row=1, column=0,padx=10,pady=10)  # CAJA DE ENTRADA FILA 1 COLUMNA 3
entry.config(bg="yellow", font="bold", border=10)# CAJA DE ENTRADA FILA 1 COLUMNA 0
#***********************************************************************************
entry = tk.Entry(window) #PARA ESCRIBIR DATO APELLIDO
entry.grid(row=1, column=1,padx=10,pady=10)  # CAJA DE ENTRADA FILA 1 COLUMNA 3
entry.config(bg="yellow", font="bold", border=10)# CAJA DE ENTRADA FILA 1 COLUMNA 0
#***********************************************************************************
entry = tk.Entry(window) #PARA ESCRIBIR DATO APELLIDO
entry.grid(row=1, column=2,padx=10,pady=10)  # CAJA DE ENTRADA FILA 1 COLUMNA 3
entry.config(bg="yellow", font="bold", border=10)# CAJA DE ENTRADA FILA 1 COLUMNA 0
#***********************************************************************************
entry = tk.Entry(window) #PARA ESCRIBIR DATO APELLIDO
entry.grid(row=2, column=0,padx=10,pady=10)  # CAJA DE ENTRADA FILA 1 COLUMNA 3
entry.config(bg="yellow", font="bold", border=10)# CAJA DE ENTRADA FILA 1 COLUMNA 0
#***********************************************************************************
entry = tk.Entry(window) #PARA ESCRIBIR DATO APELLIDO
entry.grid(row=2, column=1,padx=10,pady=10)  # CAJA DE ENTRADA FILA 1 COLUMNA 3
entry.config(bg="yellow", font="bold", border=10)# CAJA DE ENTRADA FILA 1 COLUMNA 0
#***********************************************************************************
entry = tk.Entry(window) #PARA ESCRIBIR DATO APELLIDO
entry.grid(row=2, column=2,padx=10,pady=10)  # CAJA DE ENTRADA FILA 1 COLUMNA 3
entry.config(bg="yellow", font="bold", border=10)# CAJA DE ENTRADA FILA 1 COLUMNA 0
#***********************************************************************************
entry = tk.Entry(window)

# Iniciar el bucle principal de la interfaz
window.mainloop()